name: CI/CD Pipeline for Next.js App (Improved)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      # Step 3: Cache Node modules
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Step 4: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 5: Build the Next.js app
      - name: Build Next.js app
        run: npm run build

      # Step 6: Upload build artifacts
      - name: Archive build artifacts
        run: |
          tar -czf build-artifacts.tar.gz .next public node_modules package.json package-lock.json prisma

      # Step 7: Set up SSH Agent
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 8: Copy artifacts to the server
      - name: Copy build to server
        run: |
          scp -o StrictHostKeyChecking=no build-artifacts.tar.gz ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/home/${{ secrets.SERVER_USER }}/nextjs-deploy/build-artifacts.tar.gz

      # Step 9: Deploy on server
      - name: Deploy on remote server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            # Go to deployment directory
            cd /home/yugene/Eugene/NodeApps/next-self-hosting

            # Remove old files (optional safety)
            rm -rf .next node_modules public prisma

            # Extract new build
            tar -xzf build-artifacts.tar.gz

            # Remove the archive
            rm build-artifacts.tar.gz

            # Restart PM2 process
            pm2 restart nextjs || pm2 start "node_modules/next/dist/bin/next" --name nextjs -- start -p 3000
          EOF
